package com.spring.aws.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
@DynamoDBDocument
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="person")
public class Person implements Serializable {
    @DynamoDBHashKey(attributeName ="personId")
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute
    private String personID;
    @DynamoDBAttribute
    private String personName;
    @DynamoDBAttribute
    private String personEmail;
    @DynamoDBAttribute
    private String role;
    @DynamoDBAttribute
    private Address address;
}
